import type { Metadata } from "next";
import { Courier_Prime } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import { AgentProvider } from "@/context/agent-context";

const courierPrime = Courier_Prime({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const classes = `bg-slate-800 ${courierPrime.className}`;
  return (
    <html lang="en">
      <body className={classes}>
        <AgentProvider>
          <Header />
          {children}
        </AgentProvider>
      </body>
    </html>
  );
}
